version: "3"
services:
  tc-or-grpc-server:
    image: tc-or-grpc-server:latest
    container_name: tc-or-grpc-server
    restart: always
    ports:
      - "9099:9099"    
    logging:
      driver: awslogs
      options:
        awslogs-group: /aws/ecs/tc-online-review
        awslogs-region: us-east-1
        awslogs-stream-prefix: tc-or-grpc-server
    env_file:
      - api.env        
  tc-online-review:
    image: tc-online-review:latest
    container_name: tc-online-review
    build:
      context: .
      dockerfile: ECSDockerfile    
    restart: always
    ports:
      - "8080:8080"
    environment:
      - grpc_client_or_address=localhost
      - grpc_client_or_port=9099      
    logging:
      driver: awslogs
      options:
        awslogs-group: /aws/ecs/tc-online-review
        awslogs-region: us-east-1
        awslogs-stream-prefix: tc_online_review
    volumes:
      - submissions:/nfs_shares/studiofiles/submissions
      - tcssubmissions:/nfs_shares/tcssubmissions
      - tcs-downloads:/nfs_shares/tcs-downloads
volumes:
  submissions:
  tcssubmissions:
  tcs-downloads: