version: "3"
services:
  tc-or-grpc-server:
    image: tc-or-grpc-server:latest
    container_name: tc-or-grpc-server
    hostname: tc-or-grpc-server
    restart: always
    ports:
      - "0:9099"    
    logging:
      driver: awslogs
      options:
        awslogs-group: /aws/ecs/tc-online-review
        awslogs-region: us-east-1
        awslogs-stream-prefix: tc-or-grpc-server
    env_file:
      - api.env        
  tc-online-review:
    image: tc-online-review:latest
    container_name: tc-online-review
    build:
      context: .
      dockerfile: ECSDockerfile    
    restart: always
    ports:
      - "0:8080"
    links:
      - tc-or-grpc-server
    environment:
      - grpc_client_or_address=tc-or-grpc-server
      - grpc_client_or_port=9099      
    depends_on:
      - grpc-or-server
    logging:
      driver: awslogs
      options:
        awslogs-group: /aws/ecs/tc-online-review
        awslogs-region: us-east-1
        awslogs-stream-prefix: tc_online_review
    volumes:
      - /nfs_shares/studiofiles/submissions:/nfs_shares/studiofiles/submissions
      - /nfs_shares/tcssubmissions:/nfs_shares/tcssubmissions
      - /nfs_shares/tcs-downloads:/nfs_shares/tcs-downloads