; it's for oracle sequence
; IMPORTANT: Please run the script with a account with sufficient priviledges, such as "SYSTEM". And run the test cases with another limited account, such as "topcoder"
DROP SEQUENCE SYSTEM.ID_SEQUENCE_SEQ;
CREATE SEQUENCE SYSTEM.ID_SEQUENCE_SEQ
    MINVALUE 1
    MAXVALUE 10000000
    START WITH  1
    INCREMENT BY 20
    CACHE 20;
GRANT SELECT ON SYSTEM.ID_SEQUENCE_SEQ TO scott;
DROP PUBLIC SYNONYM ID_SEQUENCE_SEQ;
CREATE PUBLIC SYNONYM ID_SEQUENCE_SEQ FOR SYSTEM.ID_SEQUENCE_SEQ;

DROP SEQUENCE SYSTEM.ORACLE_EXHAUST_SEQ;
CREATE SEQUENCE SYSTEM.ORACLE_EXHAUST_SEQ
    MINVALUE 1
    MAXVALUE 1000
    START WITH  1000
    INCREMENT BY 20
    CACHE 20;
GRANT SELECT ON SYSTEM.ORACLE_EXHAUST_SEQ TO scott;
DROP PUBLIC SYNONYM ORACLE_EXHAUST_SEQ;
CREATE PUBLIC SYNONYM ORACLE_EXHAUST_SEQ FOR SYSTEM.ORACLE_EXHAUST_SEQ;

DROP SEQUENCE SYSTEM.ORACLE_EXHAUST_LESS;
CREATE SEQUENCE SYSTEM.ORACLE_EXHAUST_LESS
    MINVALUE 1
    MAXVALUE 1000
    START WITH  990
    INCREMENT BY 20
    CACHE 20;
GRANT SELECT ON SYSTEM.ORACLE_EXHAUST_LESS TO scott;
DROP PUBLIC SYNONYM ORACLE_EXHAUST_LESS;
CREATE PUBLIC SYNONYM ORACLE_EXHAUST_LESS FOR SYSTEM.ORACLE_EXHAUST_LESS;

DROP SEQUENCE SYSTEM.ORACLE_EXHAUST_LESS_SEQ;
CREATE SEQUENCE SYSTEM.ORACLE_EXHAUST_LESS_SEQ
    MINVALUE 1
    MAXVALUE 1000
    START WITH  990
    INCREMENT BY 20
    CACHE 20;
GRANT SELECT ON SYSTEM.ORACLE_EXHAUST_LESS_SEQ TO scott;
DROP PUBLIC SYNONYM ORACLE_EXHAUST_LESS_SEQ;
CREATE PUBLIC SYNONYM ORACLE_EXHAUST_LESS_SEQ FOR SYSTEM.ORACLE_EXHAUST_LESS_SEQ;