-- Note: This file is not ready yet. Don't use it as its usage will have no effect.
--       This file is supposed to insert Aggregation Review into the database.

INSERT INTO review_item_comment (review_item_comment_id, resource_id, review_item_id, comment_type_id, content, sort, create_user, create_date, modify_user, modify_date)
  VALUES (100159, 208, 100199, 1, 'fine.', 0, 'slion', CURRENT, 'slion', CURRENT);
INSERT INTO review_item_comment (review_item_comment_id, resource_id, review_item_id, comment_type_id, content, sort, create_user, create_date, modify_user, modify_date)
  VALUES (100160, 208, 100200, 1, 'seems ok.', 0, 'slion', CURRENT, 'slion', CURRENT);
INSERT INTO review_item_comment (review_item_comment_id, resource_id, review_item_id, comment_type_id, content, sort, create_user, create_date, modify_user, modify_date)
  VALUES (100161, 208, 100201, 1, 'ok.', 0, 'slion', CURRENT, 'slion', CURRENT);
INSERT INTO review_item_comment (review_item_comment_id, resource_id, review_item_id, comment_type_id, content, sort, create_user, create_date, modify_user, modify_date)
  VALUES (100162, 208, 100202, 1, 'nice.', 0, 'slion', CURRENT, 'slion', CURRENT);
INSERT INTO review_item_comment (review_item_comment_id, resource_id, review_item_id, comment_type_id, content, sort, create_user, create_date, modify_user, modify_date)
  VALUES (100163, 208, 100203, 1, 'works.', 0, 'slion', CURRENT, 'slion', CURRENT);
INSERT INTO review_item_comment (review_item_comment_id, resource_id, review_item_id, comment_type_id, content, sort, create_user, create_date, modify_user, modify_date)
  VALUES (100164, 208, 100204, 1, '.....', 0, 'slion', CURRENT, 'slion', CURRENT);
INSERT INTO review_item_comment (review_item_comment_id, resource_id, review_item_id, comment_type_id, content, sort, create_user, create_date, modify_user, modify_date)
  VALUES (100165, 206, 100205, 3, 'aaa', 0, 'qiucx0161', CURRENT, 'qiucx0161', CURRENT);
INSERT INTO review_item_comment (review_item_comment_id, resource_id, review_item_id, comment_type_id, content, sort, create_user, create_date, modify_user, modify_date)
  VALUES (100166, 206, 100206, 3, 'bbb', 0, 'qiucx0161', CURRENT, 'qiucx0161', CURRENT);
INSERT INTO review_item_comment (review_item_comment_id, resource_id, review_item_id, comment_type_id, content, sort, create_user, create_date, modify_user, modify_date)
  VALUES (100167, 206, 100207, 3, 'ccc', 0, 'qiucx0161', CURRENT, 'qiucx0161, CURRENT);
INSERT INTO review_item_comment (review_item_comment_id, resource_id, review_item_id, comment_type_id, content, sort, create_user, create_date, modify_user, modify_date)
  VALUES (100168, 206, 100208, 3, 'ddd', 0, 'qiucx0161', CURRENT, 'qiucx0161', CURRENT);
INSERT INTO review_item_comment (review_item_comment_id, resource_id, review_item_id, comment_type_id, content, sort, create_user, create_date, modify_user, modify_date)
  VALUES (100169, 206, 100209, 3, 'eee', 0, 'qiucx0161', CURRENT, 'qiucx0161', CURRENT);
INSERT INTO review_item_comment (review_item_comment_id, resource_id, review_item_id, comment_type_id, content, sort, create_user, create_date, modify_user, modify_date)
  VALUES (100170, 206, 100210, 3, 'fff', 0, 'qiucx0161', CURRENT, 'qiucx0161', CURRENT);
INSERT INTO review_item_comment (review_item_comment_id, resource_id, review_item_id, comment_type_id, content, sort, create_user, create_date, modify_user, modify_date)
  VALUES (100171, 207, 100211, 3, 'half-score comment 1.', 0, 'ivern', CURRENT, 'ivern', CURRENT);
INSERT INTO review_item_comment (review_item_comment_id, resource_id, review_item_id, comment_type_id, content, sort, create_user, create_date, modify_user, modify_date)
  VALUES (100172, 207, 100212, 3, 'half-score comment 2.', 0, 'ivern', CURRENT, 'ivern', CURRENT);
INSERT INTO review_item_comment (review_item_comment_id, resource_id, review_item_id, comment_type_id, content, sort, create_user, create_date, modify_user, modify_date)
  VALUES (100173, 207, 100213, 3, 'half-score comment 3.', 0, 'ivern', CURRENT, 'ivern', CURRENT);
INSERT INTO review_item_comment (review_item_comment_id, resource_id, review_item_id, comment_type_id, content, sort, create_user, create_date, modify_user, modify_date)
  VALUES (100174, 207, 100214, 3, 'half-score comment 4.' 0, 'ivern', CURRENT, 'ivern', CURRENT);
INSERT INTO review_item_comment (review_item_comment_id, resource_id, review_item_id, comment_type_id, content, sort, create_user, create_date, modify_user, modify_date)
  VALUES (100175, 207, 100215, 3, 'no score comment.', 0, 'ivern', CURRENT, 'ivern', CURRENT);
INSERT INTO review_item_comment (review_item_comment_id, resource_id, review_item_id, comment_type_id, content, sort, create_user, create_date, modify_user, modify_date)
  VALUES (100176, 207, 100216, 1, 'half-score comment 5.' 0, 'ivern', CURRENT, 'ivern', CURRENT);

