INSERT INTO resource (resource_id, resource_role_id, create_user, create_date, modify_user, modify_date)
  VALUES (1000, 13, 'System', CURRENT, 'System', CURRENT);
INSERT INTO resource (resource_id, resource_role_id, project_id, create_user, create_date, modify_user, modify_date)
  VALUES (10001, 13, 1004, 'System', CURRENT, 'System', CURRENT);
INSERT INTO resource (resource_id, resource_role_id, project_id, create_user, create_date, modify_user, modify_date)
  VALUES (10002, 13, 1006, 'System', CURRENT, 'System', CURRENT);
INSERT INTO resource (resource_id, resource_role_id, project_id, create_user, create_date, modify_user, modify_date)
  VALUES (1001, 1, 1002, 'System', CURRENT, 'System', CURRENT);

INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date)
  VALUES (1000, 1, '1000', 'System', CURRENT, 'System', CURRENT);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date)
  VALUES (10001, 1, '1000', 'System', CURRENT, 'System', CURRENT);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date)
  VALUES (10002, 1, '1000', 'System', CURRENT, 'System', CURRENT);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date)
  VALUES (1001, 1, '1001', 'System', CURRENT, 'System', CURRENT);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date)
  VALUES (1001, 4, '667', 'System', CURRENT, 'System', CURRENT);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date)
  VALUES (1001, 5, '75', 'System', CURRENT, 'System', CURRENT);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date)
  VALUES (1001, 6, '07.08.2006 00:00 AM', 'System', CURRENT, 'System', CURRENT);


-- Project resources

INSERT INTO resource (resource_id, resource_role_id, project_id, project_phase_id, create_user, create_date, modify_user, modify_date)
  VALUES (200, 1, 1002, NULL, 'System', CURRENT, 'System', CURRENT);
INSERT INTO resource (resource_id, resource_role_id, project_id, project_phase_id, create_user, create_date, modify_user, modify_date)
  VALUES (201, 1, 1002, NULL, 'System', CURRENT, 'System', CURRENT);
INSERT INTO resource (resource_id, resource_role_id, project_id, project_phase_id, create_user, create_date, modify_user, modify_date)
  VALUES (202, 1, 1002, NULL, 'System', CURRENT, 'System', CURRENT);
INSERT INTO resource (resource_id, resource_role_id, project_id, project_phase_id, create_user, create_date, modify_user, modify_date)
  VALUES (203, 3, 1002, 503, 'System', CURRENT, 'System', CURRENT);
INSERT INTO resource (resource_id, resource_role_id, project_id, project_phase_id, create_user, create_date, modify_user, modify_date)
  VALUES (204, 3, 1002, 503, 'System', CURRENT, 'System', CURRENT);
INSERT INTO resource (resource_id, resource_role_id, project_id, project_phase_id, create_user, create_date, modify_user, modify_date)
  VALUES (205, 3, 1002, 503, 'System', CURRENT, 'System', CURRENT);
INSERT INTO resource (resource_id, resource_role_id, project_id, project_phase_id, create_user, create_date, modify_user, modify_date)
  VALUES (206, 7, 1002, 505, 'System', CURRENT, 'System', CURRENT);
INSERT INTO resource (resource_id, resource_role_id, project_id, project_phase_id, create_user, create_date, modify_user, modify_date)
  VALUES (207, 6, 1002, 505, 'System', CURRENT, 'System', CURRENT);
INSERT INTO resource (resource_id, resource_role_id, project_id, project_phase_id, create_user, create_date, modify_user, modify_date)
  VALUES (208, 5, 1002, 505, 'System', CURRENT, 'System', CURRENT);
INSERT INTO resource (resource_id, resource_role_id, project_id, project_phase_id, create_user, create_date, modify_user, modify_date)
  VALUES (209, 8, 1002, 508, 'System', CURRENT, 'System', CURRENT);
INSERT INTO resource (resource_id, resource_role_id, project_id, project_phase_id, create_user, create_date, modify_user, modify_date)
  VALUES (210, 9, 1002, 511, 'System', CURRENT, 'System', CURRENT);
INSERT INTO resource (resource_id, resource_role_id, project_id, create_user, create_date, modify_user, modify_date)
  VALUES (212, 13, 1002, 'System', CURRENT, 'System', CURRENT);
INSERT INTO resource (resource_id, resource_role_id, project_id, project_phase_id, create_user, create_date, modify_user, modify_date)
  VALUES (211, 10, 1002, 512, 'System', CURRENT, 'System', CURRENT);

INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date)
  VALUES (200, 1, '11889718', 'System', CURRENT, 'System', CURRENT);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date)
  VALUES (200, 4, '1702', 'System', CURRENT, 'System', CURRENT);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date)
  VALUES (200, 5, '1.0000', 'System', CURRENT, 'System', CURRENT);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date)
  VALUES (200, 6, '07.18.2006 00:00 AM', 'System', CURRENT, 'System', CURRENT);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date)
  VALUES (200, 9, '98.1345', 'System', CURRENT, 'System', CURRENT);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date)
  VALUES (200, 10, '78.6382928041', 'System', CURRENT, 'System', CURRENT);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date)
  VALUES (200, 11, '85.21947902542', 'System', CURRENT, 'System', CURRENT);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date)
  VALUES (200, 12, '1', 'System', CURRENT, 'System', CURRENT);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date)
  VALUES (201, 1, '15655112', 'System', CURRENT, 'System', CURRENT);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date)
  VALUES (201, 6, '07.16.2006 00:00 AM', 'System', CURRENT, 'System', CURRENT);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date)
  VALUES (201, 9, '95.3728', 'System', CURRENT, 'System', CURRENT);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date)
  VALUES (201, 10, '79.3725659249', 'System', CURRENT, 'System', CURRENT);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date)
  VALUES (201, 11, '84.364385023', 'System', CURRENT, 'System', CURRENT);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date)
  VALUES (201, 12, '2', 'System', CURRENT, 'System', CURRENT);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date)
  VALUES (202, 1, '1002', 'System', CURRENT, 'System', CURRENT);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date)
  VALUES (202, 6, '07.16.2006 00:00 AM', 'System', CURRENT, 'System', CURRENT);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date)
  VALUES (202, 9, '94.5692', 'System', CURRENT, 'System', CURRENT);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date)
  VALUES (202, 10, '73.4628584026', 'System', CURRENT, 'System', CURRENT);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date)
  VALUES (202, 11, '80.46274937', 'System', CURRENT, 'System', CURRENT);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date)
  VALUES (202, 12, '3', 'System', CURRENT, 'System', CURRENT);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date)
  VALUES (203, 1, '286907', 'System', CURRENT, 'System', CURRENT);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date)
  VALUES (203, 7, '500', 'System', CURRENT, 'System', CURRENT);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date)
  VALUES (203, 8, 'No', 'System', CURRENT, 'System', CURRENT);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date)
  VALUES (204, 1, '286907', 'System', CURRENT, 'System', CURRENT);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date)
  VALUES (204, 7, '500', 'System', CURRENT, 'System', CURRENT);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date)
  VALUES (204, 8, 'No', 'System', CURRENT, 'System', CURRENT);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date)
  VALUES (205, 1, '302053', 'System', CURRENT, 'System', CURRENT);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date)
  VALUES (205, 7, '500', 'System', CURRENT, 'System', CURRENT);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date)
  VALUES (205, 8, 'No', 'System', CURRENT, 'System', CURRENT);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date)
  VALUES (206, 1, '10650643', 'System', CURRENT, 'System', CURRENT);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date)
  VALUES (206, 7, '500', 'System', CURRENT, 'System', CURRENT);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date)
  VALUES (206, 8, 'No', 'System', CURRENT, 'System', CURRENT);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date)
  VALUES (207, 1, '156859', 'System', CURRENT, 'System', CURRENT);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date)
  VALUES (207, 7, '500', 'System', CURRENT, 'System', CURRENT);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date)
  VALUES (207, 8, 'No', 'System', CURRENT, 'System', CURRENT);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date)
  VALUES (208, 1, '10022398', 'System', CURRENT, 'System', CURRENT);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date)
  VALUES (208, 7, '500', 'System', CURRENT, 'System', CURRENT);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date)
  VALUES (208, 8, 'No', 'System', CURRENT, 'System', CURRENT);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date)
  VALUES (209, 1, '11770376', 'System', CURRENT, 'System', CURRENT);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date)
  VALUES (209, 7, '500', 'System', CURRENT, 'System', CURRENT);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date)
  VALUES (209, 8, 'No', 'System', CURRENT, 'System', CURRENT);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date)
  VALUES (210, 1, '299180', 'System', CURRENT, 'System', CURRENT);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date)
  VALUES (210, 7, '500', 'System', CURRENT, 'System', CURRENT);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date)
  VALUES (210, 8, 'No', 'System', CURRENT, 'System', CURRENT);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date)
  VALUES (211, 1, '1000', 'System', CURRENT, 'System', CURRENT);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date)
  VALUES (212, 1, '1000', 'System', CURRENT, 'System', CURRENT);

INSERT INTO notification (project_id, external_ref_id, notification_type_id, create_user, create_date, modify_user, modify_date)
  VALUES (1002, 1000, 1, 'System', CURRENT, 'System', CURRENT);
