insert into project_type_lu values(1, 'n', 'd', 'c',CURRENT, 'm', CURRENT);
insert into project_category_lu values(1, 1, 'n', 'd', 'c', CURRENT, 'm', current);
insert into project_status_lu values(1, 'n', 'd', 'c', CURRENT, 'm', current);
insert into phase_type_lu values(1, 'n', 'd', 'c',CURRENT, 'm', CURRENT);
insert into phase_status_lu values(1, 'n', 'd', 'c', CURRENT, 'm', current);
insert into upload_type_lu values(1, 'n', 'd', 'c',CURRENT, 'm', CURRENT);
insert into upload_type_lu values(2, 'n', 'd', 'c',CURRENT, 'm', CURRENT);
insert into upload_type_lu values(3, 'n', 'd', 'c',CURRENT, 'm', CURRENT);
insert into upload_status_lu values(1, 'n', 'd', 'c', CURRENT, 'm', current);
insert into submission_status_lu values(1, 'n', 'd', 'c', CURRENT, 'm', current);
insert into scorecard_type_lu values(1, 'n', 'd', 'c',CURRENT, 'm', CURRENT);
insert into scorecard_status_lu values(1, 'n', 'd', 'c', CURRENT, 'm', current);
insert into resource_role_lu values(1, 1, 'n', 'd', 'c', CURRENT, 'm', current);
insert into comment_type_lu values(7, 'n', 'd', 'c',CURRENT, 'm', CURRENT);
insert into comment_type_lu values(8, 'n', 'd', 'c',CURRENT, 'm', CURRENT);
insert into comment_type_lu values(10, 'n', 'd', 'c',CURRENT, 'm', CURRENT);
insert into project values (1,1,1,"creation_user",CURRENT,"modify_user",CURRENT);
insert into project_phase  values (1,1,1,1,CURRENT,CURRENT,CURRENT,CURRENT,CURRENT,1-2,"creation_user",CURRENT,"modify_user",CURRENT);
insert into resource  values (3,1,1,1,"creation_user",CURRENT,"modify_user",CURRENT);
insert into upload  values (1,1,3,1,1,"parameter","creation_user",CURRENT,"modify_user",CURRENT);
insert into upload  values (2,1,3,2,1,"parameter","creation_user",CURRENT,"modify_user",CURRENT);
insert into upload  values (3,1,3,3,1,"parameter","creation_user",CURRENT,"modify_user",CURRENT);
insert into submission  values (4,1,1,"creation_user",CURRENT,"modify_user",CURRENT);
insert into scorecard values (1,1,1,1,"name","version",0,100,"creation_user",CURRENT,"modify_user",CURRENT);
insert into review  values (1,3,4,1,'t',100,"creation_user",CURRENT,"modify_user",CURRENT);
insert into review_comment values (1,3,1,7,"content","Approved","creation_user",CURRENT,"modify_user",CURRENT);
insert into review_comment values (2,3,1,8,"content","Approved","creation_user",CURRENT,"modify_user",CURRENT);
insert into review_comment values (3,3,1,10,"content","Approved","creation_user",CURRENT,"modify_user",CURRENT);