INSERT INTO 'informix'.terms_of_use (terms_of_use_id, terms_of_use_type_id, title, url, terms_of_use_agreeability_type_id) VALUES(1, 1, 'title', 'url', 1)
INSERT INTO 'informix'.project_role_terms_of_use_xref (project_id, resource_role_id, terms_of_use_id, sort_order, group_ind) VALUES (1, 1, 1, 1, 1)
INSERT INTO 'informix'.terms_of_use (terms_of_use_id, terms_of_use_type_id, title, url, terms_of_use_agreeability_type_id) VALUES(2, 1, 'title', 'url', 0)
INSERT INTO 'informix'.project_role_terms_of_use_xref (project_id, resource_role_id, terms_of_use_id, sort_order, group_ind) VALUES (1, 2, 2, 1, 2)
INSERT INTO 'informix'.terms_of_use (terms_of_use_id, terms_of_use_type_id, title, url, terms_of_use_agreeability_type_id) VALUES(3, 1, 'title', 'url', 1)
INSERT INTO 'informix'.project_role_terms_of_use_xref (project_id, resource_role_id, terms_of_use_id, sort_order, group_ind) VALUES (1, 3, 3, 1, 3)
INSERT INTO 'informix'.terms_of_use (terms_of_use_id, terms_of_use_type_id, title, url, terms_of_use_agreeability_type_id) VALUES(4, 1, 'title', 'url', 0)
INSERT INTO 'informix'.project_role_terms_of_use_xref (project_id, resource_role_id, terms_of_use_id, sort_order, group_ind) VALUES (1, 4, 4, 1, 4)
INSERT INTO 'informix'.terms_of_use (terms_of_use_id, terms_of_use_type_id, title, url, terms_of_use_agreeability_type_id) VALUES(5, 1, 'title', 'url', 1)
INSERT INTO 'informix'.project_role_terms_of_use_xref (project_id, resource_role_id, terms_of_use_id, sort_order, group_ind) VALUES (1, 5, 5, 1, 5)
INSERT INTO 'informix'.terms_of_use (terms_of_use_id, terms_of_use_type_id, title, url, terms_of_use_agreeability_type_id) VALUES(6, 1, 'title', 'url', 0)
INSERT INTO 'informix'.project_role_terms_of_use_xref (project_id, resource_role_id, terms_of_use_id, sort_order, group_ind) VALUES (1, 1, 6, 1, 6)
INSERT INTO 'informix'.terms_of_use (terms_of_use_id, terms_of_use_type_id, title, url, terms_of_use_agreeability_type_id) VALUES(7, 1, 'title', 'url', 1)
INSERT INTO 'informix'.project_role_terms_of_use_xref (project_id, resource_role_id, terms_of_use_id, sort_order, group_ind) VALUES (1, 2, 7, 1, 7)
INSERT INTO 'informix'.terms_of_use (terms_of_use_id, terms_of_use_type_id, title, url, terms_of_use_agreeability_type_id) VALUES(8, 1, 'title', 'url', 0)
INSERT INTO 'informix'.project_role_terms_of_use_xref (project_id, resource_role_id, terms_of_use_id, sort_order, group_ind) VALUES (1, 3, 8, 1, 8)
INSERT INTO 'informix'.terms_of_use (terms_of_use_id, terms_of_use_type_id, title, url, terms_of_use_agreeability_type_id) VALUES(9, 1, 'title', 'url', 1)
INSERT INTO 'informix'.project_role_terms_of_use_xref (project_id, resource_role_id, terms_of_use_id, sort_order, group_ind) VALUES (1, 4, 9, 1, 9)
INSERT INTO 'informix'.terms_of_use (terms_of_use_id, terms_of_use_type_id, title, url, terms_of_use_agreeability_type_id) VALUES(10, 1, 'title', 'url', 0)
INSERT INTO 'informix'.project_role_terms_of_use_xref (project_id, resource_role_id, terms_of_use_id, sort_order, group_ind) VALUES (1, 5, 10, 1, 10)
INSERT INTO 'informix'.terms_of_use (terms_of_use_id, terms_of_use_type_id, title, url, terms_of_use_agreeability_type_id) VALUES(11, 1, 'title', 'url', 1)
INSERT INTO 'informix'.project_role_terms_of_use_xref (project_id, resource_role_id, terms_of_use_id, sort_order, group_ind) VALUES (1, 1, 11, 1, 11)
INSERT INTO 'informix'.terms_of_use (terms_of_use_id, terms_of_use_type_id, title, url, terms_of_use_agreeability_type_id) VALUES(12, 1, 'title', 'url', 0)
INSERT INTO 'informix'.project_role_terms_of_use_xref (project_id, resource_role_id, terms_of_use_id, sort_order, group_ind) VALUES (1, 2, 12, 1, 12)
INSERT INTO 'informix'.terms_of_use (terms_of_use_id, terms_of_use_type_id, title, url, terms_of_use_agreeability_type_id) VALUES(13, 1, 'title', 'url', 1)
INSERT INTO 'informix'.project_role_terms_of_use_xref (project_id, resource_role_id, terms_of_use_id, sort_order, group_ind) VALUES (1, 3, 13, 1, 13)
INSERT INTO 'informix'.terms_of_use (terms_of_use_id, terms_of_use_type_id, title, url, terms_of_use_agreeability_type_id) VALUES(14, 1, 'title', 'url', 0)
INSERT INTO 'informix'.project_role_terms_of_use_xref (project_id, resource_role_id, terms_of_use_id, sort_order, group_ind) VALUES (1, 4, 14, 1, 14)
INSERT INTO 'informix'.terms_of_use (terms_of_use_id, terms_of_use_type_id, title, url, terms_of_use_agreeability_type_id) VALUES(15, 1, 'title', 'url', 1)
INSERT INTO 'informix'.project_role_terms_of_use_xref (project_id, resource_role_id, terms_of_use_id, sort_order, group_ind) VALUES (1, 5, 15, 1, 15)
INSERT INTO 'informix'.terms_of_use (terms_of_use_id, terms_of_use_type_id, title, url, terms_of_use_agreeability_type_id) VALUES(16, 1, 'title', 'url', 0)
INSERT INTO 'informix'.project_role_terms_of_use_xref (project_id, resource_role_id, terms_of_use_id, sort_order, group_ind) VALUES (1, 1, 16, 1, 16)
INSERT INTO 'informix'.terms_of_use (terms_of_use_id, terms_of_use_type_id, title, url, terms_of_use_agreeability_type_id) VALUES(17, 1, 'title', 'url', 1)
INSERT INTO 'informix'.project_role_terms_of_use_xref (project_id, resource_role_id, terms_of_use_id, sort_order, group_ind) VALUES (1, 2, 17, 1, 17)
INSERT INTO 'informix'.terms_of_use (terms_of_use_id, terms_of_use_type_id, title, url, terms_of_use_agreeability_type_id) VALUES(18, 1, 'title', 'url', 0)
INSERT INTO 'informix'.project_role_terms_of_use_xref (project_id, resource_role_id, terms_of_use_id, sort_order, group_ind) VALUES (1, 3, 18, 1, 18)
INSERT INTO 'informix'.terms_of_use (terms_of_use_id, terms_of_use_type_id, title, url, terms_of_use_agreeability_type_id) VALUES(19, 1, 'title', 'url', 1)
INSERT INTO 'informix'.project_role_terms_of_use_xref (project_id, resource_role_id, terms_of_use_id, sort_order, group_ind) VALUES (1, 4, 19, 1, 19)
INSERT INTO 'informix'.terms_of_use (terms_of_use_id, terms_of_use_type_id, title, url, terms_of_use_agreeability_type_id) VALUES(20, 1, 'title', 'url', 0)
INSERT INTO 'informix'.project_role_terms_of_use_xref (project_id, resource_role_id, terms_of_use_id, sort_order, group_ind) VALUES (1, 5, 20, 1, 20)
INSERT INTO 'informix'.terms_of_use (terms_of_use_id, terms_of_use_type_id, title, url, terms_of_use_agreeability_type_id) VALUES(21, 1, 'title', 'url', 1)
INSERT INTO 'informix'.project_role_terms_of_use_xref (project_id, resource_role_id, terms_of_use_id, sort_order, group_ind) VALUES (1, 1, 21, 1, 21)
INSERT INTO 'informix'.terms_of_use (terms_of_use_id, terms_of_use_type_id, title, url, terms_of_use_agreeability_type_id) VALUES(22, 1, 'title', 'url', 0)
INSERT INTO 'informix'.project_role_terms_of_use_xref (project_id, resource_role_id, terms_of_use_id, sort_order, group_ind) VALUES (1, 2, 22, 1, 22)
INSERT INTO 'informix'.terms_of_use (terms_of_use_id, terms_of_use_type_id, title, url, terms_of_use_agreeability_type_id) VALUES(23, 1, 'title', 'url', 1)
INSERT INTO 'informix'.project_role_terms_of_use_xref (project_id, resource_role_id, terms_of_use_id, sort_order, group_ind) VALUES (1, 3, 23, 1, 23)
INSERT INTO 'informix'.terms_of_use (terms_of_use_id, terms_of_use_type_id, title, url, terms_of_use_agreeability_type_id) VALUES(24, 1, 'title', 'url', 0)
INSERT INTO 'informix'.project_role_terms_of_use_xref (project_id, resource_role_id, terms_of_use_id, sort_order, group_ind) VALUES (1, 4, 24, 1, 24)
INSERT INTO 'informix'.terms_of_use (terms_of_use_id, terms_of_use_type_id, title, url, terms_of_use_agreeability_type_id) VALUES(25, 1, 'title', 'url', 1)
INSERT INTO 'informix'.project_role_terms_of_use_xref (project_id, resource_role_id, terms_of_use_id, sort_order, group_ind) VALUES (1, 5, 25, 1, 25)
INSERT INTO 'informix'.terms_of_use (terms_of_use_id, terms_of_use_type_id, title, url, terms_of_use_agreeability_type_id) VALUES(26, 1, 'title', 'url', 0)
INSERT INTO 'informix'.project_role_terms_of_use_xref (project_id, resource_role_id, terms_of_use_id, sort_order, group_ind) VALUES (1, 1, 26, 1, 26)
INSERT INTO 'informix'.terms_of_use (terms_of_use_id, terms_of_use_type_id, title, url, terms_of_use_agreeability_type_id) VALUES(27, 1, 'title', 'url', 1)
INSERT INTO 'informix'.project_role_terms_of_use_xref (project_id, resource_role_id, terms_of_use_id, sort_order, group_ind) VALUES (1, 2, 27, 1, 27)
INSERT INTO 'informix'.terms_of_use (terms_of_use_id, terms_of_use_type_id, title, url, terms_of_use_agreeability_type_id) VALUES(28, 1, 'title', 'url', 0)
INSERT INTO 'informix'.project_role_terms_of_use_xref (project_id, resource_role_id, terms_of_use_id, sort_order, group_ind) VALUES (1, 3, 28, 1, 28)
INSERT INTO 'informix'.terms_of_use (terms_of_use_id, terms_of_use_type_id, title, url, terms_of_use_agreeability_type_id) VALUES(29, 1, 'title', 'url', 1)
INSERT INTO 'informix'.project_role_terms_of_use_xref (project_id, resource_role_id, terms_of_use_id, sort_order, group_ind) VALUES (1, 4, 29, 1, 29)
INSERT INTO 'informix'.terms_of_use (terms_of_use_id, terms_of_use_type_id, title, url, terms_of_use_agreeability_type_id) VALUES(30, 1, 'title', 'url', 0)
INSERT INTO 'informix'.project_role_terms_of_use_xref (project_id, resource_role_id, terms_of_use_id, sort_order, group_ind) VALUES (1, 5, 30, 1, 30)
INSERT INTO 'informix'.terms_of_use (terms_of_use_id, terms_of_use_type_id, title, url, terms_of_use_agreeability_type_id) VALUES(31, 1, 'title', 'url', 1)
INSERT INTO 'informix'.project_role_terms_of_use_xref (project_id, resource_role_id, terms_of_use_id, sort_order, group_ind) VALUES (1, 1, 31, 1, 31)
INSERT INTO 'informix'.terms_of_use (terms_of_use_id, terms_of_use_type_id, title, url, terms_of_use_agreeability_type_id) VALUES(32, 1, 'title', 'url', 0)
INSERT INTO 'informix'.project_role_terms_of_use_xref (project_id, resource_role_id, terms_of_use_id, sort_order, group_ind) VALUES (1, 2, 32, 1, 32)
INSERT INTO 'informix'.terms_of_use (terms_of_use_id, terms_of_use_type_id, title, url, terms_of_use_agreeability_type_id) VALUES(33, 1, 'title', 'url', 1)
INSERT INTO 'informix'.project_role_terms_of_use_xref (project_id, resource_role_id, terms_of_use_id, sort_order, group_ind) VALUES (1, 3, 33, 1, 33)
INSERT INTO 'informix'.terms_of_use (terms_of_use_id, terms_of_use_type_id, title, url, terms_of_use_agreeability_type_id) VALUES(34, 1, 'title', 'url', 0)
INSERT INTO 'informix'.project_role_terms_of_use_xref (project_id, resource_role_id, terms_of_use_id, sort_order, group_ind) VALUES (1, 4, 34, 1, 34)
INSERT INTO 'informix'.terms_of_use (terms_of_use_id, terms_of_use_type_id, title, url, terms_of_use_agreeability_type_id) VALUES(35, 1, 'title', 'url', 1)
INSERT INTO 'informix'.project_role_terms_of_use_xref (project_id, resource_role_id, terms_of_use_id, sort_order, group_ind) VALUES (1, 5, 35, 1, 35)
INSERT INTO 'informix'.terms_of_use (terms_of_use_id, terms_of_use_type_id, title, url, terms_of_use_agreeability_type_id) VALUES(36, 1, 'title', 'url', 0)
INSERT INTO 'informix'.project_role_terms_of_use_xref (project_id, resource_role_id, terms_of_use_id, sort_order, group_ind) VALUES (1, 1, 36, 1, 36)
INSERT INTO 'informix'.terms_of_use (terms_of_use_id, terms_of_use_type_id, title, url, terms_of_use_agreeability_type_id) VALUES(37, 1, 'title', 'url', 1)
INSERT INTO 'informix'.project_role_terms_of_use_xref (project_id, resource_role_id, terms_of_use_id, sort_order, group_ind) VALUES (1, 2, 37, 1, 37)
INSERT INTO 'informix'.terms_of_use (terms_of_use_id, terms_of_use_type_id, title, url, terms_of_use_agreeability_type_id) VALUES(38, 1, 'title', 'url', 0)
INSERT INTO 'informix'.project_role_terms_of_use_xref (project_id, resource_role_id, terms_of_use_id, sort_order, group_ind) VALUES (1, 3, 38, 1, 38)
INSERT INTO 'informix'.terms_of_use (terms_of_use_id, terms_of_use_type_id, title, url, terms_of_use_agreeability_type_id) VALUES(39, 1, 'title', 'url', 1)
INSERT INTO 'informix'.project_role_terms_of_use_xref (project_id, resource_role_id, terms_of_use_id, sort_order, group_ind) VALUES (1, 4, 39, 1, 39)
INSERT INTO 'informix'.terms_of_use (terms_of_use_id, terms_of_use_type_id, title, url, terms_of_use_agreeability_type_id) VALUES(40, 1, 'title', 'url', 0)
INSERT INTO 'informix'.project_role_terms_of_use_xref (project_id, resource_role_id, terms_of_use_id, sort_order, group_ind) VALUES (1, 5, 40, 1, 40)
INSERT INTO 'informix'.terms_of_use (terms_of_use_id, terms_of_use_type_id, title, url, terms_of_use_agreeability_type_id) VALUES(41, 1, 'title', 'url', 1)
INSERT INTO 'informix'.project_role_terms_of_use_xref (project_id, resource_role_id, terms_of_use_id, sort_order, group_ind) VALUES (1, 1, 41, 1, 41)
INSERT INTO 'informix'.terms_of_use (terms_of_use_id, terms_of_use_type_id, title, url, terms_of_use_agreeability_type_id) VALUES(42, 1, 'title', 'url', 0)
INSERT INTO 'informix'.project_role_terms_of_use_xref (project_id, resource_role_id, terms_of_use_id, sort_order, group_ind) VALUES (1, 2, 42, 1, 42)
INSERT INTO 'informix'.terms_of_use (terms_of_use_id, terms_of_use_type_id, title, url, terms_of_use_agreeability_type_id) VALUES(43, 1, 'title', 'url', 1)
INSERT INTO 'informix'.project_role_terms_of_use_xref (project_id, resource_role_id, terms_of_use_id, sort_order, group_ind) VALUES (1, 3, 43, 1, 43)
INSERT INTO 'informix'.terms_of_use (terms_of_use_id, terms_of_use_type_id, title, url, terms_of_use_agreeability_type_id) VALUES(44, 1, 'title', 'url', 0)
INSERT INTO 'informix'.project_role_terms_of_use_xref (project_id, resource_role_id, terms_of_use_id, sort_order, group_ind) VALUES (1, 4, 44, 1, 44)
INSERT INTO 'informix'.terms_of_use (terms_of_use_id, terms_of_use_type_id, title, url, terms_of_use_agreeability_type_id) VALUES(45, 1, 'title', 'url', 1)
INSERT INTO 'informix'.project_role_terms_of_use_xref (project_id, resource_role_id, terms_of_use_id, sort_order, group_ind) VALUES (1, 5, 45, 1, 45)
INSERT INTO 'informix'.terms_of_use (terms_of_use_id, terms_of_use_type_id, title, url, terms_of_use_agreeability_type_id) VALUES(46, 1, 'title', 'url', 0)
INSERT INTO 'informix'.project_role_terms_of_use_xref (project_id, resource_role_id, terms_of_use_id, sort_order, group_ind) VALUES (1, 1, 46, 1, 46)
INSERT INTO 'informix'.terms_of_use (terms_of_use_id, terms_of_use_type_id, title, url, terms_of_use_agreeability_type_id) VALUES(47, 1, 'title', 'url', 1)
INSERT INTO 'informix'.project_role_terms_of_use_xref (project_id, resource_role_id, terms_of_use_id, sort_order, group_ind) VALUES (1, 2, 47, 1, 47)
INSERT INTO 'informix'.terms_of_use (terms_of_use_id, terms_of_use_type_id, title, url, terms_of_use_agreeability_type_id) VALUES(48, 1, 'title', 'url', 0)
INSERT INTO 'informix'.project_role_terms_of_use_xref (project_id, resource_role_id, terms_of_use_id, sort_order, group_ind) VALUES (1, 3, 48, 1, 48)
INSERT INTO 'informix'.terms_of_use (terms_of_use_id, terms_of_use_type_id, title, url, terms_of_use_agreeability_type_id) VALUES(49, 1, 'title', 'url', 1)
INSERT INTO 'informix'.project_role_terms_of_use_xref (project_id, resource_role_id, terms_of_use_id, sort_order, group_ind) VALUES (1, 4, 49, 1, 49)
INSERT INTO 'informix'.terms_of_use (terms_of_use_id, terms_of_use_type_id, title, url, terms_of_use_agreeability_type_id) VALUES(50, 1, 'title', 'url', 0)
INSERT INTO 'informix'.project_role_terms_of_use_xref (project_id, resource_role_id, terms_of_use_id, sort_order, group_ind) VALUES (1, 5, 50, 1, 50)