INSERT INTO resource (resource_id, resource_role_id, create_user, create_date, modify_user, modify_date) VALUES(	1	,13,	'System'	,current,	'System', current);
INSERT INTO resource (resource_id, resource_role_id, create_user, create_date, modify_user, modify_date) VALUES(	2	,13,	'System'	,current,	'System', current);
INSERT INTO resource (resource_id, resource_role_id, create_user, create_date, modify_user, modify_date) VALUES(	3	,13,	'System'	,current,	'System', current);
INSERT INTO resource (resource_id, resource_role_id, create_user, create_date, modify_user, modify_date) VALUES(	4	,13,	'System'	,current,	'System', current);
INSERT INTO resource (resource_id, resource_role_id, create_user, create_date, modify_user, modify_date) VALUES(	5	,13,	'System'	,current,	'System', current);
INSERT INTO resource (resource_id, resource_role_id, create_user, create_date, modify_user, modify_date) VALUES(	6	,13,	'System'	,current,	'System', current);
INSERT INTO resource (resource_id, resource_role_id, create_user, create_date, modify_user, modify_date) VALUES(	7	,13,	'System'	,current,	'System', current);
INSERT INTO resource (resource_id, resource_role_id, create_user, create_date, modify_user, modify_date) VALUES(	8	,13,	'System'	,current,	'System', current);
INSERT INTO resource (resource_id, resource_role_id, create_user, create_date, modify_user, modify_date) VALUES(	9	,13,	'System'	,current,	'System', current);
INSERT INTO resource (resource_id, resource_role_id, create_user, create_date, modify_user, modify_date) VALUES(	10	,13,	'System'	,current,	'System', current);
INSERT INTO resource (resource_id, resource_role_id, create_user, create_date, modify_user, modify_date) VALUES(	11	,13,	'System'	,current,	'System', current);
INSERT INTO resource (resource_id, resource_role_id, create_user, create_date, modify_user, modify_date) VALUES(	12	,13,	'System'	,current,	'System', current);
INSERT INTO resource (resource_id, resource_role_id, create_user, create_date, modify_user, modify_date) VALUES(	13	,13,	'System'	,current,	'System', current);
INSERT INTO resource (resource_id, resource_role_id, create_user, create_date, modify_user, modify_date) VALUES(	14	,13,	'System'	,current,	'System', current);
INSERT INTO resource (resource_id, resource_role_id, create_user, create_date, modify_user, modify_date) VALUES(	15	,13,	'System'	,current,	'System', current);
INSERT INTO resource (resource_id, resource_role_id, create_user, create_date, modify_user, modify_date) VALUES(	16	,13,	'System'	,current,	'System', current);
INSERT INTO resource (resource_id, resource_role_id, create_user, create_date, modify_user, modify_date) VALUES(	17	,13,	'System'	,current,	'System', current);
INSERT INTO resource (resource_id, resource_role_id, create_user, create_date, modify_user, modify_date) VALUES(	18	,13,	'System'	,current,	'System', current);
INSERT INTO resource (resource_id, resource_role_id, create_user, create_date, modify_user, modify_date) VALUES(	19	,13,	'System'	,current,	'System', current);
INSERT INTO resource (resource_id, resource_role_id, create_user, create_date, modify_user, modify_date) VALUES(	20	,13,	'System'	,current,	'System', current);
INSERT INTO resource (resource_id, resource_role_id, create_user, create_date, modify_user, modify_date) VALUES(	21	,13,	'System'	,current,	'System', current);
INSERT INTO resource (resource_id, resource_role_id, create_user, create_date, modify_user, modify_date) VALUES(	22	,13,	'System'	,current,	'System', current);
INSERT INTO resource (resource_id, resource_role_id, create_user, create_date, modify_user, modify_date) VALUES(	23	,13,	'System'	,current,	'System', current);
INSERT INTO resource (resource_id, resource_role_id, create_user, create_date, modify_user, modify_date) VALUES(	24	,13,	'System'	,current,	'System', current);
INSERT INTO resource (resource_id, resource_role_id, create_user, create_date, modify_user, modify_date) VALUES(	25	,13,	'System'	,current,	'System', current);
INSERT INTO resource (resource_id, resource_role_id, create_user, create_date, modify_user, modify_date) VALUES(	26	,13,	'System'	,current,	'System', current);
INSERT INTO resource (resource_id, resource_role_id, create_user, create_date, modify_user, modify_date) VALUES(	27	,13,	'System'	,current,	'System', current);
INSERT INTO resource (resource_id, resource_role_id, create_user, create_date, modify_user, modify_date) VALUES(	28	,13,	'System'	,current,	'System', current);
INSERT INTO resource (resource_id, resource_role_id, create_user, create_date, modify_user, modify_date) VALUES(	29	,13,	'System'	,current,	'System', current);
INSERT INTO resource (resource_id, resource_role_id, create_user, create_date, modify_user, modify_date) VALUES(	30	,13,	'System'	,current,	'System', current);
INSERT INTO resource (resource_id, resource_role_id, create_user, create_date, modify_user, modify_date) VALUES(	31	,13,	'System'	,current,	'System', current);
INSERT INTO resource (resource_id, resource_role_id, create_user, create_date, modify_user, modify_date) VALUES(	32	,13,	'System'	,current,	'System', current);
INSERT INTO resource (resource_id, resource_role_id, create_user, create_date, modify_user, modify_date) VALUES(	33	,13,	'System'	,current,	'System', current);
INSERT INTO resource (resource_id, resource_role_id, create_user, create_date, modify_user, modify_date) VALUES(	34	,13,	'System'	,current,	'System', current);
INSERT INTO resource (resource_id, resource_role_id, create_user, create_date, modify_user, modify_date) VALUES(	35	,13,	'System'	,current,	'System', current);
INSERT INTO resource (resource_id, resource_role_id, create_user, create_date, modify_user, modify_date) VALUES(	36	,13,	'System'	,current,	'System', current);
INSERT INTO resource (resource_id, resource_role_id, create_user, create_date, modify_user, modify_date) VALUES(	37	,13,	'System'	,current,	'System', current);
INSERT INTO resource (resource_id, resource_role_id, create_user, create_date, modify_user, modify_date) VALUES(	38	,13,	'System'	,current,	'System', current);
INSERT INTO resource (resource_id, resource_role_id, create_user, create_date, modify_user, modify_date) VALUES(	39	,13,	'System'	,current,	'System', current);
INSERT INTO resource (resource_id, resource_role_id, create_user, create_date, modify_user, modify_date) VALUES(	40	,13,	'System'	,current,	'System', current);
INSERT INTO resource (resource_id, resource_role_id, create_user, create_date, modify_user, modify_date) VALUES(	41	,13,	'System'	,current,	'System', current);
INSERT INTO resource (resource_id, resource_role_id, create_user, create_date, modify_user, modify_date) VALUES(	42	,13,	'System'	,current,	'System', current);
INSERT INTO resource (resource_id, resource_role_id, create_user, create_date, modify_user, modify_date) VALUES(	43	,13,	'System'	,current,	'System', current);
INSERT INTO resource (resource_id, resource_role_id, create_user, create_date, modify_user, modify_date) VALUES(	44	,13,	'System'	,current,	'System', current);
INSERT INTO resource (resource_id, resource_role_id, create_user, create_date, modify_user, modify_date) VALUES(	45	,13,	'System'	,current,	'System', current);
INSERT INTO resource (resource_id, resource_role_id, create_user, create_date, modify_user, modify_date) VALUES(	46	,13,	'System'	,current,	'System', current);
INSERT INTO resource (resource_id, resource_role_id, create_user, create_date, modify_user, modify_date) VALUES(	47	,13,	'System'	,current,	'System', current);
INSERT INTO resource (resource_id, resource_role_id, create_user, create_date, modify_user, modify_date) VALUES(	48	,13,	'System'	,current,	'System', current);
INSERT INTO resource (resource_id, resource_role_id, create_user, create_date, modify_user, modify_date) VALUES(	49	,13,	'System'	,current,	'System', current);
INSERT INTO resource (resource_id, resource_role_id, create_user, create_date, modify_user, modify_date) VALUES(	50	,13,	'System'	,current,	'System', current);
INSERT INTO resource (resource_id, resource_role_id, create_user, create_date, modify_user, modify_date) VALUES(	51	,13,	'System'	,current,	'System', current);
INSERT INTO resource (resource_id, resource_role_id, create_user, create_date, modify_user, modify_date) VALUES(	52	,13,	'System'	,current,	'System', current);
INSERT INTO resource (resource_id, resource_role_id, create_user, create_date, modify_user, modify_date) VALUES(	53	,13,	'System'	,current,	'System', current);
INSERT INTO resource (resource_id, resource_role_id, create_user, create_date, modify_user, modify_date) VALUES(	54	,13,	'System'	,current,	'System', current);
INSERT INTO resource (resource_id, resource_role_id, create_user, create_date, modify_user, modify_date) VALUES(	55	,13,	'System'	,current,	'System', current);
INSERT INTO resource (resource_id, resource_role_id, create_user, create_date, modify_user, modify_date) VALUES(	56	,13,	'System'	,current,	'System', current);
INSERT INTO resource (resource_id, resource_role_id, create_user, create_date, modify_user, modify_date) VALUES(	57	,13,	'System'	,current,	'System', current);
INSERT INTO resource (resource_id, resource_role_id, create_user, create_date, modify_user, modify_date) VALUES(	58	,13,	'System'	,current,	'System', current);
INSERT INTO resource (resource_id, resource_role_id, create_user, create_date, modify_user, modify_date) VALUES(	59	,13,	'System'	,current,	'System', current);
INSERT INTO resource (resource_id, resource_role_id, create_user, create_date, modify_user, modify_date) VALUES(	60	,13,	'System'	,current,	'System', current);
INSERT INTO resource (resource_id, resource_role_id, create_user, create_date, modify_user, modify_date) VALUES(	61	,13,	'System'	,current,	'System', current);
INSERT INTO resource (resource_id, resource_role_id, create_user, create_date, modify_user, modify_date) VALUES(	62	,13,	'System'	,current,	'System', current);
INSERT INTO resource (resource_id, resource_role_id, create_user, create_date, modify_user, modify_date) VALUES(	63	,13,	'System'	,current,	'System', current);
INSERT INTO resource (resource_id, resource_role_id, create_user, create_date, modify_user, modify_date) VALUES(	64	,13,	'System'	,current,	'System', current);
INSERT INTO resource (resource_id, resource_role_id, create_user, create_date, modify_user, modify_date) VALUES(	65	,13,	'System'	,current,	'System', current);
INSERT INTO resource (resource_id, resource_role_id, create_user, create_date, modify_user, modify_date) VALUES(	66	,13,	'System'	,current,	'System', current);
INSERT INTO resource (resource_id, resource_role_id, create_user, create_date, modify_user, modify_date) VALUES(	67	,13,	'System'	,current,	'System', current);
INSERT INTO resource (resource_id, resource_role_id, create_user, create_date, modify_user, modify_date) VALUES(	68	,13,	'System'	,current,	'System', current);
INSERT INTO resource (resource_id, resource_role_id, create_user, create_date, modify_user, modify_date) VALUES(	69	,13,	'System'	,current,	'System', current);
INSERT INTO resource (resource_id, resource_role_id, create_user, create_date, modify_user, modify_date) VALUES(	70	,13,	'System'	,current,	'System', current);
INSERT INTO resource (resource_id, resource_role_id, create_user, create_date, modify_user, modify_date) VALUES(	71	,13,	'System'	,current,	'System', current);
INSERT INTO resource (resource_id, resource_role_id, create_user, create_date, modify_user, modify_date) VALUES(	72	,13,	'System'	,current,	'System', current);
INSERT INTO resource (resource_id, resource_role_id, create_user, create_date, modify_user, modify_date) VALUES(	73	,13,	'System'	,current,	'System', current);
INSERT INTO resource (resource_id, resource_role_id, create_user, create_date, modify_user, modify_date) VALUES(	74	,13,	'System'	,current,	'System', current);
INSERT INTO resource (resource_id, resource_role_id, create_user, create_date, modify_user, modify_date) VALUES(	75	,13,	'System'	,current,	'System', current);
INSERT INTO resource (resource_id, resource_role_id, create_user, create_date, modify_user, modify_date) VALUES(	76	,13,	'System'	,current,	'System', current);
INSERT INTO resource (resource_id, resource_role_id, create_user, create_date, modify_user, modify_date) VALUES(	77	,13,	'System'	,current,	'System', current);
INSERT INTO resource (resource_id, resource_role_id, create_user, create_date, modify_user, modify_date) VALUES(	78	,13,	'System'	,current,	'System', current);
INSERT INTO resource (resource_id, resource_role_id, create_user, create_date, modify_user, modify_date) VALUES(	79	,13,	'System'	,current,	'System', current);
INSERT INTO resource (resource_id, resource_role_id, create_user, create_date, modify_user, modify_date) VALUES(	80	,13,	'System'	,current,	'System', current);
INSERT INTO resource (resource_id, resource_role_id, create_user, create_date, modify_user, modify_date) VALUES(	81	,13,	'System'	,current,	'System', current);
INSERT INTO resource (resource_id, resource_role_id, create_user, create_date, modify_user, modify_date) VALUES(	82	,13,	'System'	,current,	'System', current);
INSERT INTO resource (resource_id, resource_role_id, create_user, create_date, modify_user, modify_date) VALUES(	83	,13,	'System'	,current,	'System', current);
INSERT INTO resource (resource_id, resource_role_id, create_user, create_date, modify_user, modify_date) VALUES(	84	,13,	'System'	,current,	'System', current);
INSERT INTO resource (resource_id, resource_role_id, create_user, create_date, modify_user, modify_date) VALUES(	85	,13,	'System'	,current,	'System', current);
INSERT INTO resource (resource_id, resource_role_id, create_user, create_date, modify_user, modify_date) VALUES(	86	,13,	'System'	,current,	'System', current);


INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date) VALUES(2	,1,	104355	,'System'	,Current,	'System'	,Current);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date) VALUES(3	,1,	107160	,'System'	,Current,	'System'	,Current);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date) VALUES(4	,1,	119655	,'System'	,Current,	'System'	,Current);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date) VALUES(5	,1,	128382	,'System'	,Current,	'System'	,Current);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date) VALUES(6	,1,	129063	,'System'	,Current,	'System'	,Current);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date) VALUES(7	,1,	132456	,'System'	,Current,	'System'	,Current);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date) VALUES(8	,1,	136337	,'System'	,Current,	'System'	,Current);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date) VALUES(9	,1,	142177	,'System'	,Current,	'System'	,Current);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date) VALUES(10	,1,	150148	,'System'	,Current,	'System'	,Current);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date) VALUES(11	,1,	155753	,'System'	,Current,	'System'	,Current);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date) VALUES(12	,1,	155846	,'System'	,Current,	'System'	,Current);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date) VALUES(13	,1,	156859	,'System'	,Current,	'System'	,Current);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date) VALUES(14	,1,	159052	,'System'	,Current,	'System'	,Current);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date) VALUES(15	,1,	160049	,'System'	,Current,	'System'	,Current);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date) VALUES(16	,1,	251133	,'System'	,Current,	'System'	,Current);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date) VALUES(17	,1,	251989	,'System'	,Current,	'System'	,Current);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date) VALUES(18	,1,	262467	,'System'	,Current,	'System'	,Current);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date) VALUES(19	,1,	265522	,'System'	,Current,	'System'	,Current);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date) VALUES(20	,1,	268546	,'System'	,Current,	'System'	,Current);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date) VALUES(21	,1,	271853	,'System'	,Current,	'System'	,Current);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date) VALUES(22	,1,	278287	,'System'	,Current,	'System'	,Current);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date) VALUES(23	,1,	278430	,'System'	,Current,	'System'	,Current);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date) VALUES(24	,1,	279551	,'System'	,Current,	'System'	,Current);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date) VALUES(25	,1,	287131	,'System'	,Current,	'System'	,Current);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date) VALUES(26	,1,	289521	,'System'	,Current,	'System'	,Current);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date) VALUES(27	,1,	301376	,'System'	,Current,	'System'	,Current);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date) VALUES(28	,1,	305384	,'System'	,Current,	'System'	,Current);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date) VALUES(29	,1,	309138	,'System'	,Current,	'System'	,Current);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date) VALUES(30	,1,	311237	,'System'	,Current,	'System'	,Current);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date) VALUES(31	,1,	344263	,'System'	,Current,	'System'	,Current);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date) VALUES(32	,1,	348595	,'System'	,Current,	'System'	,Current);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date) VALUES(33	,1,	2059531	,'System'	,Current,	'System'	,Current);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date) VALUES(34	,1,	7211060	,'System'	,Current,	'System'	,Current);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date) VALUES(35	,1,	7267401	,'System'	,Current,	'System'	,Current);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date) VALUES(36	,1,	7268390	,'System'	,Current,	'System'	,Current);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date) VALUES(37	,1,	7270519	,'System'	,Current,	'System'	,Current);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date) VALUES(38	,1,	7346876	,'System'	,Current,	'System'	,Current);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date) VALUES(39	,1,	7360335	,'System'	,Current,	'System'	,Current);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date) VALUES(40	,1,	7440835	,'System'	,Current,	'System'	,Current);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date) VALUES(41	,1,	7542308	,'System'	,Current,	'System'	,Current);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date) VALUES(42	,1,	100142	,'System'	,Current,	'System'	,Current);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date) VALUES(43	,1,	7545675	,'System'	,Current,	'System'	,Current);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date) VALUES(44	,1,	22089168	,'System'	,Current,	'System'	,Current);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date) VALUES(45	,1,	7546867	,'System'	,Current,	'System'	,Current);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date) VALUES(46	,1,	7575238	,'System'	,Current,	'System'	,Current);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date) VALUES(47	,1,	8351389	,'System'	,Current,	'System'	,Current);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date) VALUES(48	,1,	8358667	,'System'	,Current,	'System'	,Current);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date) VALUES(49	,1,	8502750	,'System'	,Current,	'System'	,Current);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date) VALUES(50	,1,	8520396	,'System'	,Current,	'System'	,Current);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date) VALUES(51	,1,	8547899	,'System'	,Current,	'System'	,Current);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date) VALUES(52	,1,	8548782	,'System'	,Current,	'System'	,Current);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date) VALUES(53	,1,	10053295	,'System'	,Current,	'System'	,Current);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date) VALUES(54	,1,	11793269	,'System'	,Current,	'System'	,Current);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date) VALUES(55	,1,	11823846	,'System'	,Current,	'System'	,Current);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date) VALUES(56	,1,	11867004	,'System'	,Current,	'System'	,Current);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date) VALUES(57	,1,	11968435	,'System'	,Current,	'System'	,Current);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date) VALUES(58	,1,	12005197	,'System'	,Current,	'System'	,Current);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date) VALUES(59	,1,	12030083	,'System'	,Current,	'System'	,Current);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date) VALUES(60	,1,	12032968	,'System'	,Current,	'System'	,Current);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date) VALUES(61	,1,	13344657	,'System'	,Current,	'System'	,Current);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date) VALUES(62	,1,	13406075	,'System'	,Current,	'System'	,Current);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date) VALUES(63	,1,	14810373	,'System'	,Current,	'System'	,Current);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date) VALUES(64	,1,	14859266	,'System'	,Current,	'System'	,Current);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date) VALUES(65	,1,	14882871	,'System'	,Current,	'System'	,Current);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date) VALUES(66	,1,	14990531	,'System'	,Current,	'System'	,Current);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date) VALUES(67	,1,	14999860	,'System'	,Current,	'System'	,Current);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date) VALUES(68	,1,	15193644	,'System'	,Current,	'System'	,Current);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date) VALUES(69	,1,	15213220	,'System'	,Current,	'System'	,Current);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date) VALUES(70	,1,	15545604	,'System'	,Current,	'System'	,Current);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date) VALUES(71	,1,	15599488	,'System'	,Current,	'System'	,Current);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date) VALUES(72	,1,	15966457	,'System'	,Current,	'System'	,Current);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date) VALUES(73	,1,	19746387	,'System'	,Current,	'System'	,Current);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date) VALUES(74	,1,	19796092	,'System'	,Current,	'System'	,Current);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date) VALUES(75	,1,	20001609	,'System'	,Current,	'System'	,Current);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date) VALUES(76	,1,	20114620	,'System'	,Current,	'System'	,Current);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date) VALUES(77	,1,	20353364	,'System'	,Current,	'System'	,Current);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date) VALUES(78	,1,	21043968	,'System'	,Current,	'System'	,Current);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date) VALUES(79	,1,	21196141	,'System'	,Current,	'System'	,Current);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date) VALUES(80	,1,	21246410	,'System'	,Current,	'System'	,Current);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date) VALUES(81	,1,	21355641	,'System'	,Current,	'System'	,Current);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date) VALUES(82	,1,	21654679	,'System'	,Current,	'System'	,Current);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date) VALUES(83	,1,	21713276	,'System'	,Current,	'System'	,Current);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date) VALUES(84	,1,	21770227	,'System'	,Current,	'System'	,Current);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date) VALUES(85	,1,	21940783	,'System'	,Current,	'System'	,Current);
INSERT INTO resource_info (resource_id, resource_info_type_id, value, create_user, create_date, modify_user, modify_date) VALUES(86	,1,	22015320	,'System'	,Current,	'System'	,Current);
